coverage:
  status:
    project:
      default:
        target: 0%
        threshold: 0%
        base: auto
        if_ci_failed: error

    patch:
      default:
        target: 80%
        threshold: 2%
        base: auto
        if_ci_failed: error
